// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYxAUeyDkNZ0vR4KRkOvjkYXYp7jAkwuE',
    appId: '1:580734294295:web:10a1d5f931d6bd7eb9ff52',
    messagingSenderId: '580734294295',
    projectId: 'quickensol-fc9b2',
    authDomain: 'quickensol-fc9b2.firebaseapp.com',
    storageBucket: 'quickensol-fc9b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANn1-8C2dUhB7tbQnic9P1nhc2iZOp3k0',
    appId: '1:580734294295:android:2b6911a90dfe5d59b9ff52',
    messagingSenderId: '580734294295',
    projectId: 'quickensol-fc9b2',
    storageBucket: 'quickensol-fc9b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPwCZDMtkpoTSDu4SP4KbNgieoAMMdXR0',
    appId: '1:580734294295:ios:ffbdebbe3c29585cb9ff52',
    messagingSenderId: '580734294295',
    projectId: 'quickensol-fc9b2',
    storageBucket: 'quickensol-fc9b2.appspot.com',
    iosBundleId: 'com.example.quickensol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPwCZDMtkpoTSDu4SP4KbNgieoAMMdXR0',
    appId: '1:580734294295:ios:ffbdebbe3c29585cb9ff52',
    messagingSenderId: '580734294295',
    projectId: 'quickensol-fc9b2',
    storageBucket: 'quickensol-fc9b2.appspot.com',
    iosBundleId: 'com.example.quickensol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYxAUeyDkNZ0vR4KRkOvjkYXYp7jAkwuE',
    appId: '1:580734294295:web:a1e009ccdcde4fc9b9ff52',
    messagingSenderId: '580734294295',
    projectId: 'quickensol-fc9b2',
    authDomain: 'quickensol-fc9b2.firebaseapp.com',
    storageBucket: 'quickensol-fc9b2.appspot.com',
  );
}
